server:
  port: 32202
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://receivedb:5432/receive-db
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
  application:
    name: receive-service
