server:
  port: 32201
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/storage-db
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
  application:
    name: storage-service